import Head from "next/head";
import Image from "next/image";

import Banner from "@/components/Banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1 className="text-5xl font-semibold">Netflix</h1>
        {/* <NavBar /> */}
        <Banner title="Man from Toronto" subtitle="a very funny movie" />
        {/* <Card /> */}
      </main>
    </>
  );
}
